name = "still-glade-4d20"       # the name shown in Cloudflare
main = "worker.js"              # entry‑point file
compatibility_date = "2025-07-17"

[[kv_namespaces]]
binding = "CHAT_QUOTA"
id = "86b1b3f8cdb04136912344cea25c1b68"